# Generated by Django 6.0.3 on 2026-04-01 11:03

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[accounts.validators.custom_username_validator]),
        ),
    ]
